let descripciones = [
    "No pierdas el tiempo buscando tu media naranja, ya la has encontrado.",
    "¿No tendremos un amigo en común que pueda presentarnos?",
    "Si ser sexy fuese un delito, te pasarías la vida en la cárcel.",
    "No sé besar, ¿te importaría enseñarme?",
    "¡Me encantan tus ojos! Me encantaría volver a verlos otra vez.",
    "Me encantaría verte sin maquillaje cada mañana de mi vida.",
    "Por tentaciones como tú, hay tantos pecadores como yo.",
    "Si fueras salsa me pasaría el día mojando.",
    "No creía en el amor a primera vista hasta que te vi entrar.",
    "Llevas una ropa preciosa, seguro que quedaría bien en el suelo de mi habitación.",
    "¿Podrías decirme tu nombre? Es que ayer soñé contigo, pero me desperté justo cuando me lo ibas a decir.",
    "¿Dónde puedo encontrar una cafetería cerca de aquí?... ¿Me acompañas a tomar un café?",
    "Me acabo de mudar a esta ciudad, ¿me la enseñas?",
    "¿Estoy en el cielo? Porque acabo de ver a un ángel.",
    "He leído mi horóscopo y dice que esta semana encontraré a alguien especial... creo que eres tú.",
    "¿Acaba de salir el sol o has sonreído?",
    "Mis padres me enseñaron a perseguir mis sueños, ¿puedo acompañarte a casa?",
    "Una loca como yo necesita un tornillo como tú.",
    "Desde que te he visto, he perdido el juicio. Creo que necesito un buen abogado.",
    "Disculpa, ¿te llamas Google? Porque tienes todo lo que busco.",
    "Yo no tengo la culpa de que me gustes, es tu culpa por tener todo lo que me encanta.",
    "¿Podrías prestarme un diccionario? Es que al verte me he quedado sin palabras.",
    "Quisiera tener unos hijos preciosos algún día, ¿puedo preguntar a tus padres cómo lo hicieron?",
    "¿Sabes cuánto mide el universo? Pues ya sabes cuánto me gustas.",
    "Eres tan guapo que se me ha olvidado lo que te iba a decir.",
    "No sé si eres sueño o realidad, pero si estoy soñando... no quiero despertar.",
    "¿Qué hace una estrella volando tan bajo?",
    "Hola, ¿quería saber si además de atractiva también eres simpática? ¿Lo eres?",
    "Hola, te he visto y no he podido evitar presentarme, ¿cómo te llamas?",
    "No sé si soy tu tipo, pero ¿por qué no nos damos una oportunidad para averiguarlo?",
    "¿Qué animal te gusta más; un pato o un pingüino?",
    "¿Quién miente más: los hombres o las mujeres?",
    "¿Sabes cuánto pesa un oso panda? Pues lo bastante como para romper el hielo, ¿cómo te llamas?",
    "Parece mentira que haya tardado 23 años en conocerte.",
    "Mirándote me choqué contra esa columna. Necesito tu nombre y teléfono para el seguro.",
    "Estoy escribiendo una novela, si me das tus datos, te la mando.",
    "Hueles genial, ¿has comido pizza?",
    "¿Ya crees en el amor a primera vista o paso otra vez por delante?",
    "He perdido mi número de teléfono, ¿me das el tuyo?",
    "Me gustan mucho tus ojos, sobre todo el izquierdo.",
    "Eres la única persona que conozco con dos corazones, el tuyo y el mío.",
    "Eso que haces es andar y lo demás es estropear el suelo.",
    "Espero que sepas dar el boca a boca porque me he quedado sin aliento.",
    "¿Cuánto tiempo te quedarás conmigo? ¿Preparo café o toda una vida?",
    "Yo aquí intentando no enamorarme y vienes tú con esa sonrisa.",
    "Tengo ganas de besayunarte.",
    "Disculpa que haya tardado tanto, me hubiese gustado llegar antes a tu vida.",
    "No necesito a un príncipe que me rescate, te necesito a ti.",
    "No nos conocemos y habrá que poner remedio a ese problema.",
    "Estás como para invitarte a dormir y no dormir.",
    "Iba a decirte que me gustas, pero la verdad es que me encantas.",
    "Me encanta la soltería, pero por ti me lo pensaría.",
    "¿Qué es lo peor que te han dicho por aquí?",
    "¿Qué descubrimiento ha sido más importante en tu vida: Netflix o los aguacates?",
    "Venga, pongámonos polémicos, pizza con piña… ¿sí o no?",
    "¿Eres más de gatos o de perros?",
    "Ya sé que no soy Mick Jagger, pero también me gusta el rock y sé hacer una tortilla de patatas buenísima.",
    "Me encanta tu biografía, pero me niego a aceptar que En El Camino es mejor que Cien Años de Soledad, ¿supone eso algún problema?",
    "Me gusta tu cara y me gustaría averiguar si tu personalidad es igual de increíble.",
    "Eres tan dulce que contigo cualquiera se vuelve diabético.",
    "Debes estar cansadísima, porque llevas todo el día dando vueltas por mi cabeza.",
    "Quiero ser el qué gustos tan feos tienes de tu mamá.",
    "Te advierto que un día me cansaré de tanta",
    "¿Eres real o estoy soñando?",
    "¿Por qué seguir buscando tu media naranja cuando yo puedo ser tu naranja entera?",
    "¿Acaba de salir el sol... o es que me acabas de sonreír?",
    "¿Te gustan los indios y los vaqueros? Pues dejémonos de rodeos y vayamos a tomar una cerveza juntos.",
    "Perdona, pero soy nuevo por aquí, ¿me explicas cómo llegar a tu casa?",
    "Si pudiera pedir un superpoder ahora mismo, querría ser capaz de decirte las ganas que tengo de quedar contigo.",
    "Tres son multitud, ¿y si quedamos a solas?",
    "No sé si nos hemos conocido antes o es que te he visto mucho en mis sueños.",
    "Pero, ¿cómo es posible que una estrella esté a la altura del suelo?",
    "Hoy me he comprado una agenda y me he dado cuenta de que me faltaba lo más importante. ¿El qué? Tu número de teléfono.",
    "Yo no tengo la culpa de que me gustes, la culpa es tuya por tener todo lo que me encanta.",
    "Llevas una ropa preciosa, seguro que quedaría bien en el suelo de mi habitación.",
    "¿Podrías decirme tu nombre? Es que ayer soñé contigo, pero me desperté justo cuando me lo ibas a decir.",
    "¿Dónde puedo encontrar una cafetería cerca de aquí?... ¿Me acompañas a tomar un café?",
    "Me acabo de mudar a esta ciudad, ¿me la enseñas?",
    "¿Estoy en el cielo? Porque acabo de ver a un ángel.",
    "He leído mi horóscopo y dice que esta semana encontraré a alguien especial... creo que eres tú.",
    "¿Acaba de salir el sol o has sonreído?",
    "Mis padres me enseñaron a perseguir mis sueños, ¿puedo acompañarte a casa?",
    "Una loca como yo necesita un tornillo como tú.",
    "Desde que te he visto, he perdido el juicio. Creo que necesito un buen abogado.",
    "Disculpa, ¿te llamas Google? Porque tienes todo lo que busco.",
    "Yo no tengo la culpa de que me gustes, es tu culpa por tener todo lo que me encanta.",
    "¿Podrías prestarme un diccionario? Es que al verte me he quedado sin palabras.",
    "Quisiera tener unos hijos preciosos algún día, ¿puedo preguntar a tus padres cómo lo hicieron?",
    "¿Sabes cuánto mide el universo? Pues ya sabes cuánto me gustas.",
    "Si ser sexy fuese un delito, te pasarías la vida en la cárcel.",
    "No sé besar, ¿te importaría enseñarme?",
    "¡Me encantan tus ojos! Me encantaría volver a verlos otra vez.",
    "Me encantaría verte sin maquillaje cada mañana de mi vida.",
    "Por tentaciones como tú, hay tantos pecadores como yo.",
    "Si fueras salsa me pasaría el día mojando.",
    "No creía en el amor a primera vista hasta que te vi entrar.",
    "Llevas una ropa preciosa, seguro que quedaría bien en el suelo de mi habitación.",
    "¿Podrías decirme tu nombre? Es que ayer soñé contigo, pero me desperté justo cuando me lo ibas a decir.",
    "¿Dónde puedo encontrar una cafetería cerca de aquí?... ¿Me acompañas a tomar un café?",
    "Me acabo de mudar a esta ciudad, ¿me la enseñas?"
    ];


    module.exports = descripciones;